apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    test: readiness
    purpose: demonstrate-readiness-probe
spec:
  containers:
  - name: my-container
    image: nginx:latest
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 600
    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5