apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    app:  myapp
    type: back-end
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        name: myapp
        type: back-end
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
  replicas: 3