apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    test: startup
    purpose: demonstrate-startup-probe
  name: startup-exec
spec:
  containers:
  - name: my-container
    image: nginx
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy
    startupProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      failureThreshold: 30
      periodSeconds: 10
