apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    test: startup
    purpose: demonstrate-startup-probe
spec:
  containers:
  - name: my-container
    image: busybox:latest
    args:
    - /bin/sh
    - -c
    - sleep 300
    startupProbe:
      exec:
        command:
        - cat
        - /etc/sudipta
      periodSeconds: 10
      failureThreshold: 10