apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    test: readiness
    purpose: demonstrate-readiness-probe
spec:
  containers:
  - name: my-container
    image: busybox:latest
    resources:
      limits:
        memory: 512Mi
        cpu: "1"
      requests:
        memory: 256Mi
        cpu: "0.2"
    args:
    - /bin/sh
    - -c
    - sleep 15; touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 600
    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 10
      periodSeconds: 5